### ISSUE TITLE
chap3 질문!

### ISSUE THREAD

**Issue by white-bean** [yskim0/Ewha_Data_Analysis#3]
p.180 피마 인디언 당뇨 예측에서 StandardScaler하는 부분!

로지스틱 회귀에서 숫자 데이터에 스케일링 적용하는 것이 좋다고 했는데 StandardScaler을 적용함으로써 얻는 이득이 무엇인가요? 보통 성능이 더 높아진다고 하는데 평균0, 분산1로 만드는 것이 어떤 원리로 , 왜 성능이 높아지는건지 궁금합니다.

**Comment by deblee2** [comment]
StandardScaler는 가우시안 정규 분포를 가질 수 있도록 데이터를 변환합니다. 그런데 선형 회귀, 로지스틱 회귀, SVM 등은 데이터가 가우시안 분포를 가진다는 가정하에 구현되었기 때문에 StandardScaler를 적용하므로서 성능 향상에 중요한 요소가 될 수 있습니다!

**Comment by white-bean** [comment]
감사합니다!!
